rest:
  port: 3000
  allowCORS: false

auth:
  enabled: true
  tokenSecret: "some-sekret"

database:
  log: true
  driver: postgres
  connectionString: postgresql://postgres:root@localhost:5432/pyvinci?sslmode=disable
